# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJfhnzyM2V8Fd3mkY2VIrIyoFDIb2KKI
"""

def swap_variables(a, b):
    # Temporary variable to store the value of 'a'
    temp = a

    # Assign the value of 'b' to 'a'
    a = b

    # Assign the value stored in 'temp' (which was the original value of 'a') to 'b'
    b = temp

    # Return the swapped values
    return a, b

# Main program
if __name__ == "__main__":
    # Taking input from user
    a = input("Enter the value of first variable (a): ")
    b = input("Enter the value of second variable (b): ")

    # Swapping variables
    a, b = swap_variables(a, b)

    # Displaying swapped variables
    print("After swapping:")
    print("Value of first variable (a):", a)
    print("Value of second variable (b):", b)

def swap_variables(a, b):
    # Swapping variables
    a = a + b
    b = a - b
    a = a - b

    # Return the swapped values
    return a, b

# Main program
if __name__ == "__main__":
    # Taking input from user
    a = int(input("Enter the value of first variable (a): "))
    b = int(input("Enter the value of second variable (b): "))

    # Swapping variables
    a, b = swap_variables(a, b)

    # Displaying swapped variables
    print("After swapping:")
    print("Value of first variable (a):", a)
    print("Value of second variable (b):", b)